# Generated by Django 4.2.11 on 2024-05-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqpost',
            name='answer',
        ),
        migrations.AddField(
            model_name='mcqpost',
            name='description',
            field=models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
