# Generated by Django 4.2.11 on 2024-05-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigen', '0002_remove_mcqpost_answer_mcqpost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqpost',
            name='answer',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
